spring.application.name=shoppingcart

app.jwt.secret=${JWT_SECRET:K7gNU3sdo+OL0wNhqoVWhr3g6s1xYv72ol/pe/Unols=}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.tryItOutEnabled=true
